### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by shin31120** [ShayanJa/RL_trader#2]
I'm studying with your code. But I can't do it no more. 

When I run trader.py, 

Traceback (most recent call last):
  File "C:/Users/shin3/PycharmProjects/test/binance/RL_trader-master/trader.py", line 30, in <module>
    live_env = LiveBinanceEnvironment("BTC", "USDT", .002, 15, 15, 10, 12, 26)
  File "C:\Users\shin3\PycharmProjects\test\binance\RL_trader-master\environment.py", line 167, in __init__
    self.initial_balance = self.client.get_asset_balance(asset='USDT')['free']
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 1793, in get_asset_balance
    res = self.get_account(**params)
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 1768, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 180, in _request
    kwargs['data']['signature'] = self._generate_signature(kwargs['data'])
  File "C:\Users\shin3\.conda\envs\py37\lib\site-packages\binance\client.py", line 135, in _generate_signature
    m = hmac.new(self.API_SECRET.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256)
AttributeError: 'NoneType' object has no attribute 'encode'

Please help me how to solve this problem.

**Comment by ShayanJa** [comment]
Hello, Did you figure it out? Did you set env vars?

**Comment by ShayanJa** [comment]
I added a requirements file too and .env.example, hopefully that helps

**Comment by shin31120** [comment]
Thanks a lot for your reply. I forgot manything, so I'll study again, and then ask you. thanks 
------ Original Message ------
Date: Tuesday, Apr 20, 2021 02:57:26 PM

**Comment by polonezu** [comment]
yes i have the same problem

**Comment by polonezu1985** [comment]
File "C:\Users\shin3.conda\envs\py37\lib\site-packages\binance\client.py", line 135, in _generate_signature
m = hmac.new(self.API_SECRET.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256)
AttributeError: 'NoneType' object has no attribute 'encode'!!please i need help <this errror make me crazzy

**Comment by ShayanJa** [comment]
Did you set your env variables?

**Comment by polonezu1985** [comment]
Give me exemple please,en where i must set env variables ,i'm beginner!!thank,s

**Comment by polonezu1985** [comment]
raise Exception("Model needed")
